version: '3'
services:
  app-vue:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - 3000:8080
    image: 'vue3:3.0'
#    working_dir: /vue3-app
    volumes:
      - ./:/vue3-app




